/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "s3eIOSGameCenter.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef const char*(*s3eIOSGameCenterGetErrorString_t)();
typedef s3eIOSGameCenterError(*s3eIOSGameCenterGetError_t)();
typedef      int32(*s3eIOSGameCenterGetInt_t)(s3eIOSGameCenterProperty property);
typedef const char*(*s3eIOSGameCenterGetString_t)(s3eIOSGameCenterProperty property);
typedef  s3eResult(*s3eIOSGameCenterAuthenticate_t)(s3eIOSGameCenterAuthenticationCallbackFn authenticationCB, void* userData);
typedef  s3eResult(*s3eIOSGameCenterLoadFriends_t)(s3eIOSGameCenterLoadFriendsCallbackFn loadFriendsCB, void* userData);
typedef      int32(*s3eIOSGameCenterGetFriendIDs_t)(char** friendIDs, int maxFriendIDs);
typedef  s3eResult(*s3eIOSGameCenterQueryPlayersActivity_t)(s3eIOSGameCenterActivityCallbackFn queryActivityCB, int playerGroup, void* userData);
typedef  s3eResult(*s3eIOSGameCenterSetInviteHandler_t)(s3eIOSGameCenterInviteCallbackFn callback);
typedef  s3eResult(*s3eIOSGameCenterMatchmakerFindPlayersForHostedRequest_t)(s3eIOSGameCenterMatchRequest* request, s3eIOSGameCenterFindPlayersCallbackFn findPlayersCB, void* userData);
typedef  s3eResult(*s3eIOSGameCenterMatchmakerGUI_t)(s3eIOSGameCenterMatchRequest* request, s3eIOSGameCenterMatchCallbacks* callbacks);
typedef  s3eResult(*s3eIOSGameCenterMatchmakerHostedGUI_t)(s3eIOSGameCenterMatchRequest* request, s3eIOSGameCenterFindPlayersCallbackFn findPlayersCB);
typedef    s3eBool(*s3eIOSGameCenterInviteAcceptGUI_t)(void* inviteID, s3eIOSGameCenterMatchCallbacks* callbacks);
typedef  s3eResult(*s3eIOSGameCenterReleaseInvite_t)(void* inviteID);
typedef  s3eResult(*s3eIOSGameCenterMatchmakerCreateMatch_t)(s3eIOSGameCenterMatchRequest* request, s3eIOSGameCenterCreateMatchCallbackFn createMatchCB, s3eIOSGameCenterMatchCallbacks* callbacks);
typedef  s3eResult(*s3eIOSGameCenterMatchmakerAddPlayersToMatch_t)(s3eIOSGameCenterMatchRequest* request, s3eIOSGameCenterAddPlayersToMatchCallbackFn addPlayersCB, void* userData);
typedef       void(*s3eIOSGameCenterCancelMatchmaking_t)();
typedef  s3eResult(*s3eIOSGameCenterMatchDisconnect_t)();
typedef      int32(*s3eIOSGameCenterMatchGetInt_t)(s3eIOSGameCenterMatchProperty property);
typedef const char*(*s3eIOSGameCenterPlayerGetString_t)(s3eIOSGameCenterPlayer* player, s3eIOSGameCenterPlayerProperty property);
typedef      int32(*s3eIOSGameCenterPlayerGetInt_t)(s3eIOSGameCenterPlayer* player, s3eIOSGameCenterPlayerProperty property);
typedef      int32(*s3eIOSGameCenterGetPlayerIDsInMatch_t)(char** playerIDs, int maxPlayerIDs);
typedef  s3eResult(*s3eIOSGameCenterGetPlayers_t)(const char** playerIDs, int numPlayers, s3eIOSGameCenterGetPlayersCallbackFn callback);
typedef       void(*s3eIOSGameCenterReleasePlayers_t)(s3eIOSGameCenterPlayer** players, int numPlayers);
typedef  s3eResult(*s3eIOSGameCenterSendDataToPlayers_t)(char** playerIDs, int numPlayers, const void* data, int dataLen, s3eIOSGameCenterMatchSendDataMode mode);
typedef  s3eResult(*s3eIOSGameCenterSendDataToAllPlayers_t)(const void* data, int dataLen, s3eIOSGameCenterMatchSendDataMode mode);
typedef  s3eResult(*s3eIOSGameCenterLeaderboardLoadCategories_t)(s3eIOSGameCenterLeaderboardLoadCategoriesCallbackFn loadCategoriesCB);
typedef  s3eResult(*s3eIOSGameCenterLeaderboardShowGUI_t)(const char* category, s3eIOSGameCenterTimeScope timeScope);
typedef s3eIOSGameCenterLeaderboard*(*s3eIOSGameCenterCreateLeaderboard_t)(const char** playerIDs, int numPlayers);
typedef      int32(*s3eIOSGameCenterLeaderboardGetInt_t)(s3eIOSGameCenterLeaderboard* leaderboard, s3eIOSGameCenterLeaderboardProperty property);
typedef  s3eResult(*s3eIOSGameCenterLeaderboardSetInt_t)(s3eIOSGameCenterLeaderboard* leaderboard, s3eIOSGameCenterLeaderboardProperty property, int32 value);
typedef const char*(*s3eIOSGameCenterLeaderboardGetString_t)(s3eIOSGameCenterLeaderboard* leaderboard, s3eIOSGameCenterLeaderboardProperty property);
typedef  s3eResult(*s3eIOSGameCenterLeaderboardSetString_t)(s3eIOSGameCenterLeaderboard* leaderboard, s3eIOSGameCenterLeaderboardProperty property, const char* value);
typedef  s3eResult(*s3eIOSGameCenterLeaderboardLoadScores_t)(s3eIOSGameCenterLeaderboard* leaderboard, s3eIOSGameCenterLoadScoresCallbackFn loadScoresCB);
typedef  s3eResult(*s3eIOSGameCenterLeaderboardRelease_t)(s3eIOSGameCenterLeaderboard* leaderboard);
typedef  s3eResult(*s3eIOSGameCenterReportScore_t)(int64 score, const char* category, s3eIOSGameCenterOperationCompleteCallbackFn callback);
typedef  s3eResult(*s3eIOSGameCenterAchievementsShowGUI_t)();
typedef  s3eResult(*s3eIOSGameCenterLoadAchievementInfo_t)(s3eIOSGameCenterLoadAchievementInfoCallbackFn callback);
typedef  s3eResult(*s3eIOSGameCenterLoadAchievements_t)(s3eIOSGameCenterLoadAchievementsCallbackFn callback);
typedef  s3eResult(*s3eIOSGameCenterAchievementsReset_t)();
typedef  s3eResult(*s3eIOSGameCenterReportAchievement_t)(const char* name, int percentComplete, s3eIOSGameCenterOperationCompleteCallbackFn callback);
typedef    s3eBool(*s3eGameCentreVoiceChatIsAllowed_t)();
typedef  s3eResult(*s3eIOSGameCenterSetVoiceChatUpdateHandler_t)(s3eIOSGameCenterVoiceChatUpdateCallbackFn voiceChatUpdateCB);
typedef s3eIOSGameCenterVoiceChat*(*s3eIOSGameCenterVoiceChatOpenChannel_t)(const char* channelName);
typedef  s3eResult(*s3eIOSGameCenterVoiceChatCloseChannel_t)(s3eIOSGameCenterVoiceChat* channel);
typedef      int32(*s3eIOSGameCenterVoiceChatGetInt_t)(s3eIOSGameCenterVoiceChat* channel, s3eIOSGameCenterVoiceChatProperty property);
typedef  s3eResult(*s3eIOSGameCenterVoiceChatSetInt_t)(s3eIOSGameCenterVoiceChat* channel, s3eIOSGameCenterVoiceChatProperty property, int32 value);
typedef  s3eResult(*s3eIOSGameCenterVoiceChatSetMute_t)(s3eIOSGameCenterVoiceChat* channel, const char* playerID, s3eBool mute);

/**
 * struct that gets filled in by s3eIOSGameCenterRegister
 */
typedef struct s3eIOSGameCenterFuncs
{
    s3eIOSGameCenterGetErrorString_t m_s3eIOSGameCenterGetErrorString;
    s3eIOSGameCenterGetError_t m_s3eIOSGameCenterGetError;
    s3eIOSGameCenterGetInt_t m_s3eIOSGameCenterGetInt;
    s3eIOSGameCenterGetString_t m_s3eIOSGameCenterGetString;
    s3eIOSGameCenterAuthenticate_t m_s3eIOSGameCenterAuthenticate;
    s3eIOSGameCenterLoadFriends_t m_s3eIOSGameCenterLoadFriends;
    s3eIOSGameCenterGetFriendIDs_t m_s3eIOSGameCenterGetFriendIDs;
    s3eIOSGameCenterQueryPlayersActivity_t m_s3eIOSGameCenterQueryPlayersActivity;
    s3eIOSGameCenterSetInviteHandler_t m_s3eIOSGameCenterSetInviteHandler;
    s3eIOSGameCenterMatchmakerFindPlayersForHostedRequest_t m_s3eIOSGameCenterMatchmakerFindPlayersForHostedRequest;
    s3eIOSGameCenterMatchmakerGUI_t m_s3eIOSGameCenterMatchmakerGUI;
    s3eIOSGameCenterMatchmakerHostedGUI_t m_s3eIOSGameCenterMatchmakerHostedGUI;
    s3eIOSGameCenterInviteAcceptGUI_t m_s3eIOSGameCenterInviteAcceptGUI;
    s3eIOSGameCenterReleaseInvite_t m_s3eIOSGameCenterReleaseInvite;
    s3eIOSGameCenterMatchmakerCreateMatch_t m_s3eIOSGameCenterMatchmakerCreateMatch;
    s3eIOSGameCenterMatchmakerAddPlayersToMatch_t m_s3eIOSGameCenterMatchmakerAddPlayersToMatch;
    s3eIOSGameCenterCancelMatchmaking_t m_s3eIOSGameCenterCancelMatchmaking;
    s3eIOSGameCenterMatchDisconnect_t m_s3eIOSGameCenterMatchDisconnect;
    s3eIOSGameCenterMatchGetInt_t m_s3eIOSGameCenterMatchGetInt;
    s3eIOSGameCenterPlayerGetString_t m_s3eIOSGameCenterPlayerGetString;
    s3eIOSGameCenterPlayerGetInt_t m_s3eIOSGameCenterPlayerGetInt;
    s3eIOSGameCenterGetPlayerIDsInMatch_t m_s3eIOSGameCenterGetPlayerIDsInMatch;
    s3eIOSGameCenterGetPlayers_t m_s3eIOSGameCenterGetPlayers;
    s3eIOSGameCenterReleasePlayers_t m_s3eIOSGameCenterReleasePlayers;
    s3eIOSGameCenterSendDataToPlayers_t m_s3eIOSGameCenterSendDataToPlayers;
    s3eIOSGameCenterSendDataToAllPlayers_t m_s3eIOSGameCenterSendDataToAllPlayers;
    s3eIOSGameCenterLeaderboardLoadCategories_t m_s3eIOSGameCenterLeaderboardLoadCategories;
    s3eIOSGameCenterLeaderboardShowGUI_t m_s3eIOSGameCenterLeaderboardShowGUI;
    s3eIOSGameCenterCreateLeaderboard_t m_s3eIOSGameCenterCreateLeaderboard;
    s3eIOSGameCenterLeaderboardGetInt_t m_s3eIOSGameCenterLeaderboardGetInt;
    s3eIOSGameCenterLeaderboardSetInt_t m_s3eIOSGameCenterLeaderboardSetInt;
    s3eIOSGameCenterLeaderboardGetString_t m_s3eIOSGameCenterLeaderboardGetString;
    s3eIOSGameCenterLeaderboardSetString_t m_s3eIOSGameCenterLeaderboardSetString;
    s3eIOSGameCenterLeaderboardLoadScores_t m_s3eIOSGameCenterLeaderboardLoadScores;
    s3eIOSGameCenterLeaderboardRelease_t m_s3eIOSGameCenterLeaderboardRelease;
    s3eIOSGameCenterReportScore_t m_s3eIOSGameCenterReportScore;
    s3eIOSGameCenterAchievementsShowGUI_t m_s3eIOSGameCenterAchievementsShowGUI;
    s3eIOSGameCenterLoadAchievementInfo_t m_s3eIOSGameCenterLoadAchievementInfo;
    s3eIOSGameCenterLoadAchievements_t m_s3eIOSGameCenterLoadAchievements;
    s3eIOSGameCenterAchievementsReset_t m_s3eIOSGameCenterAchievementsReset;
    s3eIOSGameCenterReportAchievement_t m_s3eIOSGameCenterReportAchievement;
    s3eGameCentreVoiceChatIsAllowed_t m_s3eGameCentreVoiceChatIsAllowed;
    s3eIOSGameCenterSetVoiceChatUpdateHandler_t m_s3eIOSGameCenterSetVoiceChatUpdateHandler;
    s3eIOSGameCenterVoiceChatOpenChannel_t m_s3eIOSGameCenterVoiceChatOpenChannel;
    s3eIOSGameCenterVoiceChatCloseChannel_t m_s3eIOSGameCenterVoiceChatCloseChannel;
    s3eIOSGameCenterVoiceChatGetInt_t m_s3eIOSGameCenterVoiceChatGetInt;
    s3eIOSGameCenterVoiceChatSetInt_t m_s3eIOSGameCenterVoiceChatSetInt;
    s3eIOSGameCenterVoiceChatSetMute_t m_s3eIOSGameCenterVoiceChatSetMute;
} s3eIOSGameCenterFuncs;

static s3eIOSGameCenterFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x79dc6b96, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: s3eIOSGameCenter");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x79dc6b96, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eIOSGameCenterAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eBool s3eExtIOSGameCenterAvailable()
{
    return s3eIOSGameCenterAvailable();
}

const char* s3eIOSGameCenterGetErrorString()
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[0] func: s3eIOSGameCenterGetErrorString"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eIOSGameCenterGetErrorString();
}

s3eIOSGameCenterError s3eIOSGameCenterGetError()
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[1] func: s3eIOSGameCenterGetError"));

    if (!_extLoad())
        return (s3eIOSGameCenterError)0;

    return g_Ext.m_s3eIOSGameCenterGetError();
}

int32 s3eIOSGameCenterGetInt(s3eIOSGameCenterProperty property)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[2] func: s3eIOSGameCenterGetInt"));

    if (!_extLoad())
        return -1;

    return g_Ext.m_s3eIOSGameCenterGetInt(property);
}

const char* s3eIOSGameCenterGetString(s3eIOSGameCenterProperty property)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[3] func: s3eIOSGameCenterGetString"));

    if (!_extLoad())
        return "";

    return g_Ext.m_s3eIOSGameCenterGetString(property);
}

s3eResult s3eIOSGameCenterAuthenticate(s3eIOSGameCenterAuthenticationCallbackFn authenticationCB, void* userData)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[4] func: s3eIOSGameCenterAuthenticate"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterAuthenticate(authenticationCB, userData);
}

s3eResult s3eIOSGameCenterLoadFriends(s3eIOSGameCenterLoadFriendsCallbackFn loadFriendsCB, void* userData)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[5] func: s3eIOSGameCenterLoadFriends"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterLoadFriends(loadFriendsCB, userData);
}

int32 s3eIOSGameCenterGetFriendIDs(char** friendIDs, int maxFriendIDs)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[6] func: s3eIOSGameCenterGetFriendIDs"));

    if (!_extLoad())
        return -1;

    return g_Ext.m_s3eIOSGameCenterGetFriendIDs(friendIDs, maxFriendIDs);
}

s3eResult s3eIOSGameCenterQueryPlayersActivity(s3eIOSGameCenterActivityCallbackFn queryActivityCB, int playerGroup, void* userData)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[7] func: s3eIOSGameCenterQueryPlayersActivity"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterQueryPlayersActivity(queryActivityCB, playerGroup, userData);
}

s3eResult s3eIOSGameCenterSetInviteHandler(s3eIOSGameCenterInviteCallbackFn callback)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[8] func: s3eIOSGameCenterSetInviteHandler"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterSetInviteHandler(callback);
}

s3eResult s3eIOSGameCenterMatchmakerFindPlayersForHostedRequest(s3eIOSGameCenterMatchRequest* request, s3eIOSGameCenterFindPlayersCallbackFn findPlayersCB, void* userData)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[9] func: s3eIOSGameCenterMatchmakerFindPlayersForHostedRequest"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterMatchmakerFindPlayersForHostedRequest(request, findPlayersCB, userData);
}

s3eResult s3eIOSGameCenterMatchmakerGUI(s3eIOSGameCenterMatchRequest* request, s3eIOSGameCenterMatchCallbacks* callbacks)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[10] func: s3eIOSGameCenterMatchmakerGUI"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterMatchmakerGUI(request, callbacks);
}

s3eResult s3eIOSGameCenterMatchmakerHostedGUI(s3eIOSGameCenterMatchRequest* request, s3eIOSGameCenterFindPlayersCallbackFn findPlayersCB)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[11] func: s3eIOSGameCenterMatchmakerHostedGUI"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterMatchmakerHostedGUI(request, findPlayersCB);
}

s3eBool s3eIOSGameCenterInviteAcceptGUI(void* inviteID, s3eIOSGameCenterMatchCallbacks* callbacks)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[12] func: s3eIOSGameCenterInviteAcceptGUI"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterInviteAcceptGUI(inviteID, callbacks);
}

s3eResult s3eIOSGameCenterReleaseInvite(void* inviteID)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[13] func: s3eIOSGameCenterReleaseInvite"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterReleaseInvite(inviteID);
}

s3eResult s3eIOSGameCenterMatchmakerCreateMatch(s3eIOSGameCenterMatchRequest* request, s3eIOSGameCenterCreateMatchCallbackFn createMatchCB, s3eIOSGameCenterMatchCallbacks* callbacks)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[14] func: s3eIOSGameCenterMatchmakerCreateMatch"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterMatchmakerCreateMatch(request, createMatchCB, callbacks);
}

s3eResult s3eIOSGameCenterMatchmakerAddPlayersToMatch(s3eIOSGameCenterMatchRequest* request, s3eIOSGameCenterAddPlayersToMatchCallbackFn addPlayersCB, void* userData)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[15] func: s3eIOSGameCenterMatchmakerAddPlayersToMatch"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterMatchmakerAddPlayersToMatch(request, addPlayersCB, userData);
}

void s3eIOSGameCenterCancelMatchmaking()
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[16] func: s3eIOSGameCenterCancelMatchmaking"));

    if (!_extLoad())
        return;

    g_Ext.m_s3eIOSGameCenterCancelMatchmaking();
}

s3eResult s3eIOSGameCenterMatchDisconnect()
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[17] func: s3eIOSGameCenterMatchDisconnect"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterMatchDisconnect();
}

int32 s3eIOSGameCenterMatchGetInt(s3eIOSGameCenterMatchProperty property)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[18] func: s3eIOSGameCenterMatchGetInt"));

    if (!_extLoad())
        return -1;

    return g_Ext.m_s3eIOSGameCenterMatchGetInt(property);
}

const char* s3eIOSGameCenterPlayerGetString(s3eIOSGameCenterPlayer* player, s3eIOSGameCenterPlayerProperty property)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[19] func: s3eIOSGameCenterPlayerGetString"));

    if (!_extLoad())
        return "";

    return g_Ext.m_s3eIOSGameCenterPlayerGetString(player, property);
}

int32 s3eIOSGameCenterPlayerGetInt(s3eIOSGameCenterPlayer* player, s3eIOSGameCenterPlayerProperty property)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[20] func: s3eIOSGameCenterPlayerGetInt"));

    if (!_extLoad())
        return -1;

    return g_Ext.m_s3eIOSGameCenterPlayerGetInt(player, property);
}

int32 s3eIOSGameCenterGetPlayerIDsInMatch(char** playerIDs, int maxPlayerIDs)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[21] func: s3eIOSGameCenterGetPlayerIDsInMatch"));

    if (!_extLoad())
        return -1;

    return g_Ext.m_s3eIOSGameCenterGetPlayerIDsInMatch(playerIDs, maxPlayerIDs);
}

s3eResult s3eIOSGameCenterGetPlayers(const char** playerIDs, int numPlayers, s3eIOSGameCenterGetPlayersCallbackFn callback)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[22] func: s3eIOSGameCenterGetPlayers"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterGetPlayers(playerIDs, numPlayers, callback);
}

void s3eIOSGameCenterReleasePlayers(s3eIOSGameCenterPlayer** players, int numPlayers)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[23] func: s3eIOSGameCenterReleasePlayers"));

    if (!_extLoad())
        return;

    g_Ext.m_s3eIOSGameCenterReleasePlayers(players, numPlayers);
}

s3eResult s3eIOSGameCenterSendDataToPlayers(char** playerIDs, int numPlayers, const void* data, int dataLen, s3eIOSGameCenterMatchSendDataMode mode)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[24] func: s3eIOSGameCenterSendDataToPlayers"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterSendDataToPlayers(playerIDs, numPlayers, data, dataLen, mode);
}

s3eResult s3eIOSGameCenterSendDataToAllPlayers(const void* data, int dataLen, s3eIOSGameCenterMatchSendDataMode mode)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[25] func: s3eIOSGameCenterSendDataToAllPlayers"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterSendDataToAllPlayers(data, dataLen, mode);
}

s3eResult s3eIOSGameCenterLeaderboardLoadCategories(s3eIOSGameCenterLeaderboardLoadCategoriesCallbackFn loadCategoriesCB)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[26] func: s3eIOSGameCenterLeaderboardLoadCategories"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterLeaderboardLoadCategories(loadCategoriesCB);
}

s3eResult s3eIOSGameCenterLeaderboardShowGUI(const char* category, s3eIOSGameCenterTimeScope timeScope)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[27] func: s3eIOSGameCenterLeaderboardShowGUI"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterLeaderboardShowGUI(category, timeScope);
}

s3eIOSGameCenterLeaderboard* s3eIOSGameCenterCreateLeaderboard(const char** playerIDs, int numPlayers)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[28] func: s3eIOSGameCenterCreateLeaderboard"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eIOSGameCenterCreateLeaderboard(playerIDs, numPlayers);
}

int32 s3eIOSGameCenterLeaderboardGetInt(s3eIOSGameCenterLeaderboard* leaderboard, s3eIOSGameCenterLeaderboardProperty property)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[29] func: s3eIOSGameCenterLeaderboardGetInt"));

    if (!_extLoad())
        return -1;

    return g_Ext.m_s3eIOSGameCenterLeaderboardGetInt(leaderboard, property);
}

s3eResult s3eIOSGameCenterLeaderboardSetInt(s3eIOSGameCenterLeaderboard* leaderboard, s3eIOSGameCenterLeaderboardProperty property, int32 value)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[30] func: s3eIOSGameCenterLeaderboardSetInt"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterLeaderboardSetInt(leaderboard, property, value);
}

const char* s3eIOSGameCenterLeaderboardGetString(s3eIOSGameCenterLeaderboard* leaderboard, s3eIOSGameCenterLeaderboardProperty property)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[31] func: s3eIOSGameCenterLeaderboardGetString"));

    if (!_extLoad())
        return "";

    return g_Ext.m_s3eIOSGameCenterLeaderboardGetString(leaderboard, property);
}

s3eResult s3eIOSGameCenterLeaderboardSetString(s3eIOSGameCenterLeaderboard* leaderboard, s3eIOSGameCenterLeaderboardProperty property, const char* value)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[32] func: s3eIOSGameCenterLeaderboardSetString"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterLeaderboardSetString(leaderboard, property, value);
}

s3eResult s3eIOSGameCenterLeaderboardLoadScores(s3eIOSGameCenterLeaderboard* leaderboard, s3eIOSGameCenterLoadScoresCallbackFn loadScoresCB)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[33] func: s3eIOSGameCenterLeaderboardLoadScores"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterLeaderboardLoadScores(leaderboard, loadScoresCB);
}

s3eResult s3eIOSGameCenterLeaderboardRelease(s3eIOSGameCenterLeaderboard* leaderboard)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[34] func: s3eIOSGameCenterLeaderboardRelease"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterLeaderboardRelease(leaderboard);
}

s3eResult s3eIOSGameCenterReportScore(int64 score, const char* category, s3eIOSGameCenterOperationCompleteCallbackFn callback)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[35] func: s3eIOSGameCenterReportScore"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterReportScore(score, category, callback);
}

s3eResult s3eIOSGameCenterAchievementsShowGUI()
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[36] func: s3eIOSGameCenterAchievementsShowGUI"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterAchievementsShowGUI();
}

s3eResult s3eIOSGameCenterLoadAchievementInfo(s3eIOSGameCenterLoadAchievementInfoCallbackFn callback)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[37] func: s3eIOSGameCenterLoadAchievementInfo"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterLoadAchievementInfo(callback);
}

s3eResult s3eIOSGameCenterLoadAchievements(s3eIOSGameCenterLoadAchievementsCallbackFn callback)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[38] func: s3eIOSGameCenterLoadAchievements"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterLoadAchievements(callback);
}

s3eResult s3eIOSGameCenterAchievementsReset()
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[39] func: s3eIOSGameCenterAchievementsReset"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterAchievementsReset();
}

s3eResult s3eIOSGameCenterReportAchievement(const char* name, int percentComplete, s3eIOSGameCenterOperationCompleteCallbackFn callback)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[40] func: s3eIOSGameCenterReportAchievement"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterReportAchievement(name, percentComplete, callback);
}

s3eBool s3eGameCentreVoiceChatIsAllowed()
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[41] func: s3eGameCentreVoiceChatIsAllowed"));

    if (!_extLoad())
        return S3E_FALSE;

    return g_Ext.m_s3eGameCentreVoiceChatIsAllowed();
}

s3eResult s3eIOSGameCenterSetVoiceChatUpdateHandler(s3eIOSGameCenterVoiceChatUpdateCallbackFn voiceChatUpdateCB)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[42] func: s3eIOSGameCenterSetVoiceChatUpdateHandler"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterSetVoiceChatUpdateHandler(voiceChatUpdateCB);
}

s3eIOSGameCenterVoiceChat* s3eIOSGameCenterVoiceChatOpenChannel(const char* channelName)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[43] func: s3eIOSGameCenterVoiceChatOpenChannel"));

    if (!_extLoad())
        return NULL;

    return g_Ext.m_s3eIOSGameCenterVoiceChatOpenChannel(channelName);
}

s3eResult s3eIOSGameCenterVoiceChatCloseChannel(s3eIOSGameCenterVoiceChat* channel)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[44] func: s3eIOSGameCenterVoiceChatCloseChannel"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterVoiceChatCloseChannel(channel);
}

int32 s3eIOSGameCenterVoiceChatGetInt(s3eIOSGameCenterVoiceChat* channel, s3eIOSGameCenterVoiceChatProperty property)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[45] func: s3eIOSGameCenterVoiceChatGetInt"));

    if (!_extLoad())
        return -1;

    return g_Ext.m_s3eIOSGameCenterVoiceChatGetInt(channel, property);
}

s3eResult s3eIOSGameCenterVoiceChatSetInt(s3eIOSGameCenterVoiceChat* channel, s3eIOSGameCenterVoiceChatProperty property, int32 value)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[46] func: s3eIOSGameCenterVoiceChatSetInt"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterVoiceChatSetInt(channel, property, value);
}

s3eResult s3eIOSGameCenterVoiceChatSetMute(s3eIOSGameCenterVoiceChat* channel, const char* playerID, s3eBool mute)
{
    IwTrace(IOSGAMECENTER_VERBOSE, ("calling s3eIOSGameCenter[47] func: s3eIOSGameCenterVoiceChatSetMute"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eIOSGameCenterVoiceChatSetMute(channel, playerID, mute);
}
